### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by 2byrds** [WebOfTrust/signify-ts#11]
Task List:
- [x]  Document Identifier Requests
- [x]  Document Agent Requests
- [x] Document Registry Requests
- [x] Document Schema Requests
- [x] Document Challenge Requests
- [x] Document Contact Requests
- [x] Document Credential Requests

**Comment by 2byrds** [comment]
related to https://github.com/WebOfTrust/keria/issues/24

**Comment by m00sey** [comment]
How is this going?

I was going to introduce JSDoc today, start that process, thoughts @2byrds @rodolfomiranda @AlexAndrei98 @pfeairheller

**Comment by rodolfomiranda** [comment]
merged with PR #85
