### ISSUE TITLE
Integration Tests in Signify Client Libraries

### ISSUE THREAD

**Issue by m00sey** [WebOfTrust/signify-ts#123]
There are two sets of integration tests under `scripts` and `integration` scripts.

- [x] Align usage/invocation into a single location
- [ ] Initially add basic integration tests like single sig etc 
- [ ] Further address integration tests using witness network

**Comment by lenkan** [comment]
@m00sey this can probably be closed now? We have integration tests and the other script directory is removed.

**Comment by lenkan** [comment]
Closing as this is now implemented. Feel free to re-open if you disagree.
