### ISSUE TITLE
Consider moving away from tsdx

### ISSUE THREAD

**Issue by lenkan** [WebOfTrust/signify-ts#130]
tsdx seems to be largely an abandoned project. See

- https://github.com/jaredpalmer/tsdx/issues/1058
- https://github.com/jaredpalmer/tsdx/issues/1065

It will probably cause some headaches going forward upgrading node versions, testing frameworks, linting and so on. I suggest removing it and just use `tsc` directly.

We probably do not need to build minified builds in the npm package. `signify-ts` can be published as an ES Module package. Then it is up to the user of the package to decide if they want to bundle it with their application code, for example if they are building a web app.

**Comment by rodolfomiranda** [comment]
Based on the linked comments, agree on moving away. I have no opinion on alternatives.
