### ISSUE TITLE
Decide what to do with the remaining scripts in /scripts directory

### ISSUE THREAD

**Issue by lenkan** [WebOfTrust/signify-ts#164]
Since #161, all scripts in /integration-scripts are converted to run as integration tests. In the /scripts directory, we have these files. It is a mix of .ts, .py and shell scripts. Some to be used together. Currently they are not being exercised in any workflow, so hard to tell if all of them still work.

- [client.ts](examples/scripts/client.ts)
- [create_agent.py](examples/scripts/create_agent.py)
- [create_multisig_aid.py](examples/scripts/create_multisig_aid.py)
- [create_person_aid.py](examples/scripts/create_person_aid.py)
- [create_rpys.py](examples/scripts/create_rpys.py)
- [delegator.sh](examples/scripts/delegator.sh)
- [env.sh](examples/scripts/env.sh)
- [get.py](examples/scripts/get.py)
- [list_aids.py](examples/scripts/list_aids.py)
- [list_notifications.py](examples/scripts/list_notifications.py)
- [list_notifications.ts](examples/scripts/list_notifications.ts)
- [make_endroles.ts](examples/scripts/make_endroles.ts)
- [multisig_endrole.py](examples/scripts/multisig_endrole.py)
- [multisig-create-credential.sh](examples/scripts/multisig-create-credential.sh)
- [multisig-create-credential.ts](examples/scripts/multisig-create-credential.ts)
- [multisig-kli.sh](examples/scripts/multisig-kli.sh)
- [multisig-sigpy.sh](examples/scripts/multisig-sigpy.sh)
- [multisig-sigts.sh](examples/scripts/multisig-sigts.sh)
- [package.json](examples/scripts/package.json)
- [stream_escrows.py](examples/scripts/stream_escrows.py)
- [tsconfig.json](examples/scripts/tsconfig.json)

Do we want to keep some of them? If so, which?

**Comment by pfeairheller** [comment]
I propose creating a `signify-integration` repo and moving these scripts there.  That will make setting up all the dependencies easier and clean up this repo.

**Comment by kentbull** [comment]
I suggest referencing the signify-integration repo from the signify-ts repo so people know signify-integration exists and can factor it into their CI/CI pipeplines.
