### ISSUE TITLE
Decide what to do with the examples/signify-react-ts project

### ISSUE THREAD

**Issue by lenkan** [WebOfTrust/signify-ts#165]
By inspection, I can tell the code in here has not been kept up to date with the recent changes, so it will not work in all scenarios. The `Credentials.tsx` file for example is not updated.

Should we keep it? If yes, we probably need to add some steps to the workflow to test that it works. If we do that, we can decide what level to keep it at:

- Static type-checking. Could be sufficient, but currently there are a lot of `any` types which will effectively turn off typechecking.
- Unit testing. Personally I do not see much benefit in this since it is a testing project in itself.
- E2E testing. Could be run with e.g. puppeteer to ensure that the code works in a browser environment. But is probably a bit more work than it is worth at the moment.

**Comment by kentbull** [comment]
I agree that we should keep this example in the codebase. I would be willing to help maintain it. So many recent changes are part of why we haven't updated it. With Phil's recent work https://github.com/WebOfTrust/signify-ts/pull/166 being complete then we can have an end-to-end flow with issue, admit, and present so now is a good time to update the webapp.

Having a sample one in this repo seems like a good idea and I agree that the tests for this sample app should be run along with tests for the repo.

**Comment by pfeairheller** [comment]
Discussed on 12/7 dev call, decision to move to its own repo.

**Comment by kentbull** [comment]
This is addressed by https://github.com/WebOfTrust/signify-ts/pull/170
