### ISSUE TITLE
Local AID creation and management API requests

### ISSUE THREAD

**Issue by 2byrds** [WebOfTrust/signify-ts#17]
Task List:
- [x] AID inception request
- [x] AID Rotation request
- [x] AID Interaction request
- [x] List AIDs request
- [x] Delete AID request
- [x] Create service request
- [x] Delete service request

depends on https://github.com/WebOfTrust/keria/issues/17

**Comment by rodolfomiranda** [comment]
@2byrds , what are the `service request` festures?
