### ISSUE TITLE
Rotate should use next threshold as default value

### ISSUE THREAD

**Issue by daviddm** [WebOfTrust/signify-ts#183]
When building the next state for rotation it uses the current threshold `state.kt` to build the next state.

https://github.com/WebOfTrust/signify-ts/blob/2a95620742a5a28cb1d27468e13a1597b3cc08dd/src/keri/app/aiding.ts#L296

If I'm understanding the rotation logic correctly it should use the `let isith = state.nt` instead?

If this is the only place we build a new state the fix is easy.
But I'm not that up to speed of the entire code base. Are there more places?

When looking at signifypy they seem to have the same bug.

https://github.com/WebOfTrust/signifypy/blob/8f086a60ad15d81a78dfc3653af9e1fa5f775ac1/src/signify/app/aiding.py#L133

However Keri seems to use the next threshold when building the state.

https://github.com/WebOfTrust/keripy/blob/67eece0c00be7318f01bdf507621824e45c03bca/src/keri/app/habbing.py#L1219

**Comment by m00sey** [comment]
@pfeairheller @SmithSamuelM can we get clarification on how this effects partial rotation?
