### ISSUE TITLE
Implement HSM/TEE Callouts for external key pairs

### ISSUE THREAD

**Issue by 2byrds** [WebOfTrust/signify-ts#19]
Look at how the other key management classes are implemented and create a generic interface so that different implementations can be plugged in.
We will create separate issues for specific implementations (android, iOS, etc.)
Task List:
- [ ] Review salty, randy, and external keeper (stubbed) in Keeping repository
- [ ] Create generic interface that works for all three (salty, randy, group)

related to https://github.com/WebOfTrust/keria/issues/14

**Comment by rodolfomiranda** [comment]
support for external modules were added in PR #109
