### ISSUE TITLE
Multisig AID as credential recipient fails to receive the issued credential

### ISSUE THREAD

**Issue by Arsh-Sandhu** [WebOfTrust/signify-ts#190]
When using a Multisig AID as the recipient during credential issuance, it fails to receive the credential even after calling the `submitAdmit` function for each member of the Multisig AID. I have written a [multisig-holder.test.ts](https://github.com/Arsh-Sandhu/signify-ts/blob/multisig-holder/examples/integration-scripts/multisig-holder.test.ts) script to test issuing credential to a multisig holder AID, based on the [multisig-holder.py](https://github.com/WebOfTrust/signifypy/blob/development/scripts/multisig-holder.py) script in `Signifypy`.
 In Signifypy, members of a multisig holder are successfully receiving credentials after Phil fixed the multisig admit issue in [KERIA PR #164](https://github.com/WebOfTrust/keria/pull/164) and I updated the  `multisig-holder.py` script in [ in PR #102](https://github.com/WebOfTrust/signifypy/pull/102)(yet to be merged).

**Comment by m00sey** [comment]
This is blocking some members of the community

**Comment by m00sey** [comment]
There is a suggestion in #193

**Comment by Arsh-Sandhu** [comment]
Closing this issue as it is resolved now. Updated `multisig-holder.test.ts`  script with commit [b4b3bf3](https://github.com/Arsh-Sandhu/signify-ts/commit/b4b3bf3095597fbae14c230292975a144d5122b1)
