### ISSUE TITLE
Issuer cannot grant to a multisig prefix

### ISSUE THREAD

**Issue by nkongsuwan** [WebOfTrust/signify-ts#193]
Currently, an issuer cannot directly grant to a multisig prefix.

This is demonstrated in PR #184, I had three clients where `client0` is an issuer while `client1` and `client2` are a multisig receiver. `client0` has resolved the multisig group's OOBI, and I tried to send a grant the credential to the multisig prefix as follow.

```
// This doesn't work
await client0.exchanges().sendFromEvents('delegator', 'credential', grant, gsigs, end, [multisigPrefix]);
```

This doesn't work, but the script below works. 
```
// This works
await client0.exchanges().sendFromEvents('delegator', 'credential', grant, gsigs, end, [aid1['prefix'], aid2['prefix']]);
```

**Comment by lenkan** [comment]
I have had the same issue. See discord conversation here: https://discord.com/channels/1148629222647148624/1148734044545228831/1184175010517098586

> Question about OOBIing with a multisig AID. I was trying to implement multisig admit using signify. Most often when resolving oobis, we use the oobis().get("alias", "agent") function to get the OOBI endpoint for the agent of the AID. When I use this OOBI to add the holder contact, the IPEX grant message only reaches one of the holder members.
>
> I noticed in signifypy, https://github.com/WebOfTrust/signifypy/blob/development/scripts/multisig-holder.py#L113, that OOBI url is manually created and it does not point to a specific agent. This is what I had to do as well to get it working in signify-ts.
> 
> Currently, it seems like the KERIA endpoint used to generate an oobi for an AID only allows to get OOBI urls for agent or witness, i.e. the role parameter. Any thoughts on this? Currently I am just constructing the OOBI manually  <keri-message-url>/oobi/<group-aid>.

I have currently worked around it by constructing the OOBI url "manually" as done in signifypy. But there is probably another fix out there.

**Comment by nkongsuwan** [comment]
@lenkan Thank you for the suggestion. If we change the default `role` for the `oobis.get`, would it not affect the default behavior of all OOBI implementations for single-signature AIDs?

**Comment by nkongsuwan** [comment]
I forgot to mention that I have tried @lenkan's suggestion to manually edit the OOBI URL and it works! 

However, I don't really understand how KERIA internally resolves OOBI, and I am not sure if changing the default behavior will break something. So I will leave that task to someone more knowledgeable than me.

**Comment by lenkan** [comment]
Just adding to this that it is also what is being done in the new multisig-holder.test.ts file. See here: https://github.com/WebOfTrust/signify-ts/blob/c64e00695e1f2a767b946dcaa84e3864eb6cd8f7/examples/integration-scripts/multisig-holder.test.ts#L396

**Comment by nkongsuwan** [comment]
I will close the issue for now. I will instead create an issue in Keria.
