### ISSUE TITLE
Fix GitHub actions for tests and add codecoverage

### ISSUE THREAD

**Issue by pfeairheller** [WebOfTrust/signify-ts#2]
The current GitHub actions don't run the tests correctly, we need to update those and then add code coverage and a coverage badge.

**Comment by pfeairheller** [comment]
Just run the unit tests and coverage report.

**Comment by AlexAndrei98** [comment]
Sweet that is all that is running at the [moment](https://github.com/WebOfTrust/signify-ts/blob/main/.github/workflows/main.yml@9fe7d32242168e60e7806f40ab9ceb0837464e55)
[on PR open](https://github.com/WebOfTrust/signify-ts/actions/runs/4940158864)
[on merging to main](https://github.com/WebOfTrust/signify-ts/actions/runs/4941889652)
