### ISSUE TITLE
Excessive bundling size due to importing entire math.js library 

### ISSUE THREAD

**Issue by lenkan** [WebOfTrust/signify-ts#226]
See instructions here: https://mathjs.org/docs/custom_bundling.html#bundle-size

I did some testing and you can reduce the mathjs bundle contribution from ~500kb to ~80kb. By using the named exports, you can enable tree-shaking.

# Before:

```
// math.ts
import { create, all } from "mathjs"

const math = create(all)
export const math;

// tholder.ts
import math from "../../math.ts"
```

[meta.json](https://github.com/WebOfTrust/signify-ts/files/14402750/meta.json)
![image](https://github.com/WebOfTrust/signify-ts/assets/5889538/1dc71d38-4383-4763-99eb-4e93d11fcacc)

# After:

```
//tholder.ts
import { fraction, sum, format } from "mathjs";
```

[meta.json](https://github.com/WebOfTrust/signify-ts/files/14402760/meta.json)
![image](https://github.com/WebOfTrust/signify-ts/assets/5889538/991bf8a2-dd90-4fff-a4a1-912e59b86fdf)

You can upload the meta.json files to https://esbuild.github.io/analyze/ yourself to explore.

The meta.json files are generated by esbuild

```
npx esbuild --bundle src/index.ts --metafile=meta.json --outfile=out.js --platform=node --minify --analyze
```

**Comment by kentbull** [comment]
Nice work!

**Comment by lenkan** [comment]
Reopened because a PR for this was never submitted. Adding it now.
