### ISSUE TITLE
Individual integration-script run fails when TEST_ENVIRONMENT=local

### ISSUE THREAD

**Issue by edeykholt** [WebOfTrust/signify-ts#229]
Repro steps:
I was able to run all the integration tests and test-setup-single-client.test.ts and they pass.
signify-ts# TEST_ENVIRONMENT=local npx jest examples/integration-scripts/test-setup-single-client.test.ts

Results:  
Expected http://127.0.01..., but received http://keria....

...
 FAIL  examples/integration-scripts/test-setup-single-client.test.ts (55.817 s)
  test-setup-single-client
    ✓ step1 (26 ms)
    ✕ step2 (21 ms)

  ● test-setup-single-client › step2

    expect(received).toEqual(expected) // deep equality

    Expected: "http://127.0.0.1:3902/oobi/ELUrT1f9RRsqfaEGh_TA3A99HZqL-qfg5dnpJfIuJcPv/agent/EC60ue9GOpQGrLBlS9T0dO6JkBTbv3V05Y4O730QBBoc"
    Received: "http://keria:3902/oobi/ELUrT1f9RRsqfaEGh_TA3A99HZqL-qfg5dnpJfIuJcPv/agent/EC60ue9GOpQGrLBlS9T0dO6JkBTbv3V05Y4O730QBBoc"

      33 |         switch (env.preset) {
      34 |             case 'local':
    > 35 |                 expect(name1_oobi).toEqual(
         |                                    ^
      36 |                     `http://127.0.0.1:3902/oobi/${name1_id}/agent/EC60ue9GOpQGrLBlS9T0dO6JkBTbv3V05Y4O730QBBoc`
      37 |                 );
      38 |                 expect(oobi.oobis[0]).toEqual(

      at Object.<anonymous> (test-setup-single-client.test.ts:35:36)

**Comment by psteniusubi** [comment]
The "local" environment is for the scenario where you don't want to use docker-compose.yaml to run the required services "vLEI-server", "kli witness demo" and "keria". 

For keria the default config file [demo-witness-oobis.json](https://github.com/WebOfTrust/keria/blob/development/scripts/keri/cf/demo-witness-oobis.json) is not fully compatible with the "docker" environment. I'm using a config file like this to start keria for "local" environment: 

```
{
  "dt": "2023-12-07T14:49:30.863592+00:00",
  "keria": {
    "dt": "2023-12-07T14:49:30.863592+00:00",
    "curls": [
      "http://127.0.0.1:3902/"
    ]
  },
  "iurls": [
    "http://127.0.0.1:5642/oobi/BBilc4-L3tFUnfM_wJr4S4OJanAv_VmF_dJNN6vkf2Ha/controller",
    "http://127.0.0.1:5643/oobi/BLskRTInXnMxWaGqcpSyMgo0nYbalW99cGZESrz3zapM/controller",
    "http://127.0.0.1:5644/oobi/BIKKuvBwpmDVA4Ds-EpL5bt9OqPzWPja2LigFYZN2YfX/controller",
    "http://127.0.0.1:5645/oobi/BM35JN8XeJSEfpxopjn5jr7tAHCE5749f0OobhMLCorE/controller",
    "http://127.0.0.1:5646/oobi/BIj15u5V11bkbtAxMA7gcNJZcax-7TgaBMLsQnMHpYHP/controller",
    "http://127.0.0.1:5647/oobi/BF2rZTW79z4IXocYRQnjjsOuvFUQv-ptCf8Yltd7PfsM/controller"
  ]
}
```
