### ISSUE TITLE
Add integration tests replicating signifypy

### ISSUE THREAD

**Issue by rodolfomiranda** [WebOfTrust/signify-ts#44]
- [x] init
- [x] salty
- [x] randy
- [x] witnesses
- [x] delegation
- [x] multisig
- [x] extern
- [x] query
- [x] multitenant
- [ ] passcode rotation
- [ ] passcode rotation x1000
- [ ] recreate client

**Comment by lenkan** [comment]
@rodolfomiranda Do you think we can close this issue? We have an issue for supporting passcode rotation in keria https://github.com/WebOfTrust/keria/issues/222. So perhaps we should just add the integration test as part of that work? Or we can create a separate issue here for testing the passcode rotation once the feature is implemented?

**Comment by rodolfomiranda** [comment]
Yes. It's an old one
