### ISSUE TITLE
Keystore creation and request signing.

### ISSUE THREAD

**Issue by pfeairheller** [WebOfTrust/signify-ts#8]
## Inception

A Signify client will initialize itself by asking for the passcode and using it to create (passcode is bran that is stretched to become a ed25519 seed) the AEID (non-transferable identifier) for both keystore encryption (ed25519 key -> x25519 key) and request signing.  Alongside that AEID key, the signify client has the option to create one of two things:

1. A second pre-rotated key AEID' and returning the passcode for that key to the controller to save as a "recovery key", sending a Blake3 hash of the AEID' to the Agent as the prior next digest.
2. A random salt for a hierarchically deterministic key chain from which is will generate AEID'(0) returning the salt to the controller to save as the "recovery key" (how to handle index?) sending a Blake3 hash of the AEID'(0) to the Agent as the prior next digest.

The choice between a random AEID' and one based on an HD key chain is a tradeoff between usability and security.  Using the random AEID' requires the Signify client to generate a new AEID returning a new passcode to the controller as the new "recovery key" for each rotation.  An HD keychain would allow the controller the opportunity to keep the same "recovery key" between rotations at the expense of some predictability of the next keys.

A Signify client will send the AEID and a Black3 hash of AEID' to the Agent to create a key store, for example in a POST to `/keystore/signify-0`

```json
{
    "aeid": "BPreeb3HxvtWDv4M81sqG7oJcH3FRp5InzvZdHV-vu-3",
    "ndig": "EBhBRqVbqhhP7Ciah5pMIOdsY5Mm1ITm2Fjqb028tylu"
}
```

In this example, the Agent will create a keystore using `signify-0` as the name, AEID is the current encryption public key for the key store and the current signing public key for requests to the agent for key store `signify-0`.  All other API requests to the agent for keystore `signify-0` will need to be signed with the private key for the AEID of this keystore.  

## Rotation
To perform a rotation of the AEID, the Signify client would perform a PUT to the `/keystore/signify-0` endpoint with AEID' now in the`aeid` field and signed by the private key of AEID'.  The Agent will verify that the prior next digest is a Blake3 hash of AEID' and that the current request is signed by the private key of AEID' and replace the current AEID with AEID'.  In addition, the Signify client will return a Blake3 hash of a new prior next key as determine by the choice between random and HD key chains.  With a random key generation strategy, a new "recovery key" must be returned to the controller to save in a safe place for the next rotation.  With HD key chain, no new "recovery key" is needed.

```json
{
    "aeid": "BDZbG0DmL0Q4eaRSzWNNjhaEZUvZRYPZ3z7Q90zTmOA6",
    "ndig": "EA_F5PWSZCN1Bns19Ns_DIsMGTuIKR-QPorkBfUM1_fU"
}
```

## Outstanding Issues

- [ ] For HD key chain, is it safe to start with the salt and generate keys until we find the current AEID when performing a rotation or will the user need to save a "current index"?
- [ ] When performing a rotation, when and how are the keys re-encrypted?   It seems that they must be included in the PUT call to `/keystore/{name}` so the newly encrypted keys are saved in one "transaction" with the new AEID.  Is that the correct assumption?

**Comment by SmithSamuelM** [comment]
A recovery key or pre-rotated key on a key store has limited utility. I the unlock key is ever compromised then that attacker has access to all the private keys and a recovery rotation does not fix that. The main value of  pre-rotation is to maintain control or an identifier and all the reputation associated with an identifier. It does not provide any value to protect data because once the data is compromised there is no recovery of the compromise.

**Comment by pfeairheller** [comment]
Built into this approach (but not mentioned anywhere) was my assumption that we were switching to symmetric encryption so the rotation was simply to protect api request signing, not encryption.  

If it's still not worth the trouble, I won't argue with removing the complexity.

**Comment by SmithSamuelM** [comment]
If we are tying signing and encryption together with encryption being to protect a keystore then the signing can use ephemeral keys. 

I am worried a little that we are doing a dumbed down version of KERI pre-rotation without doing an analysis of what that means in terms of security.

**Comment by SmithSamuelM** [comment]
Using a strong hashing algorithm like Argon2 for an HDK does not make any of the keys linkable to each other. The primary weakness of an HDK with a salt is that if the salt itself is ever compromised then all the keys are compromised.  But since the SALT does not need to ever be exposed it can be protected.

**Comment by SmithSamuelM** [comment]
As I think about it some more. Since KEL management is all done in the cloud in signify. The signify client could use full blown KERI AIDS to sign API requests. Indeed, the AID that the request is about could be the one to sign with. The client has to download the key state and the encrypted private signing keys for that keysstate, that request to bootstrap would be unsigned but all other requests could be signed after that. Or each signify client could have an account AID and when the client attaches it asks for its keystate and encrypted private key.

**Comment by SmithSamuelM** [comment]
Maybe instead of signifypy where should just have keri agent (which will be python) and then a signify interface to keri agent. because signifypy doesn’t convey that its the cloud agent but that its a python client.

**Comment by pfeairheller** [comment]
> I am worried a little that we are doing a dumbed down version of KERI pre-rotation

Yes, that is exactly what I was trying to do while accounting for the following limitations:

1. No storage on the client.
2. Usability for the library by limiting the amount of information the user would need to provide for each operation.
3. Not implementing full KERI in TypeScript.

Any addition ephemeral keys we create means the private keys have to be stored somewhere which means encrypted on the cloud or provided by the user.  I can't get past the chicken and egg problem with keys and the API.  If we rely just on encryption of the keys, we'd expose an API to download all encrypted key material so that the client can decrypt it to get the signing keys needed for all subsequent API calls.  I have a bad feeling about providing unfettered access to the encrypted key material to allow anyone to take it off line and try to brute force it.

So I keep coming back to a single passcode to generate ed25519 signing keys and generate the x25519 encryption keys from there so the user only has to provide one passcode.   I am attempting to protect that single key so that users can recover in the event of compromise.  Perhaps separating encryption and signing  to different keys and coming up with a different approach for making that "usable".  

Off the time of my mind, something as simple as making the user enter a 42 character passcode that we split in half to generate 2 different keys, one for signing and one for encrypting.  In this way, exposing the signing public key does not weaken the encrypting key and compromise of the signing key will still protect the AID keys.

Probably need a deeper discussion about how to solve this problem but regardless your point about pre-rotation is heard loud and clear and maybe we just need to bite the bullet and implement transferable AIDs on the client.

**Comment by pfeairheller** [comment]
> Maybe instead of signifypy where should just have keri agent (which will be python) and then a signify interface to keri agent. because signifypy doesn’t convey that its the cloud agent but that its a python client.

signifypy is the Python implementation of Signify which can contain an agent a client or (hopefully) both.

**Comment by SmithSamuelM** [comment]
> I have a bad feeling about providing unfettered access to the encrypted key material to allow anyone to take it off line and try to brute force it.

The bad feeling is misplaced.  Strong encryption can’t be brute forced. By design its computationally infeasible. No different than publishing the hashes of public keys in the KEL next key list. Anyone already has unfettered access to those hashes. Symmetrically encrypted private keys  with strong encryption are likewise computationally infeasible to brute force.  So given access to the encrypted private keys is not a problem and it solves the chicken and egg problem.

**Comment by SmithSamuelM** [comment]
Encryption keys are only weakened when the corpus of data encrypted reaches a really really big number. So its not a problem for us.  And we can have just one AID be the account AID for signing APIs and make it rotatable on a regular basis thereby nullifying any weakness.  Recall that anyone snooping on the Keri Signify Cloud agent could see the encrypted keys anyway.

**Comment by pfeairheller** [comment]
Ok great, without that concern this solution becomes much more straight forward.  I'll rework the design in the description of this issue.
